### PR TITLE
Added action to block and unblock messages.

### PR DESCRIPTION
**Pull request by marcosnc**
Fixes https://github.com/decentraland/catalyst/issues/113

### CODE REVIEW

**Review by nchamo — COMMENTED** [review]
Great work!

I just realized that we don't have a test that sends a wrong signature and verifies that the request failed. Could you add one?

Most tests are here https://github.com/decentraland/catalyst/blob/197fa44cf0eb75d8750ffd28bfcd20d86688396a/content/test/integration/denylist/Denylist.spec.ts#L22

**Comment by marcosnc** [comment]
> Great work!
> 
> I just realized that we don't have a test that sends a wrong signature and verifies that the request failed. Could you add one?
> 
> Most tests are here
> 
> https://github.com/decentraland/catalyst/blob/197fa44cf0eb75d8750ffd28bfcd20d86688396a/content/test/integration/denylist/Denylist.spec.ts#L22

Sure!

**Review by nchamo — APPROVED** [review]
Great work!

**Review by agusaldasoro — APPROVED** [review]
Nice!

**Pull request merged**
